/**
 * Represents a Fortnite basic access token:
 * * `LAUNCHER_WINDOWS`
 * * `FORTNITE_WINDOWS`
 * * `FORTNITE_IOS`
 */
interface BasicToken {
  LAUNCHER_WINDOWS: string;
  FORTNITE_WINDOWS: string;
  FORTNITE_IOS: string;
  FORTNITE_SWITCH: string;
}

const basicToken: BasicToken = Object.freeze({
  LAUNCHER_WINDOWS:
    "MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=",
  FORTNITE_WINDOWS:
    "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=",
  FORTNITE_IOS:
    "MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=",
  FORTNITE_SWITCH:
    "NTIyOWRjZDNhYzM4NDUyMDhiNDk2NjQ5MDkyZjI1MWI6ZTNiZDJkM2UtYmY4Yy00ODU3LTllN2QtZjNkOTQ3ZDIyMGM3=",
});

export default basicToken;
